Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/websocket?serverTimezone=Asia/Seoul
    username: root
    password: 1105
  devtools:
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false

  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftlh


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

